<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE595jMg\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE595jMg/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE595jMg.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE595jMg\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerE595jMg\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'E595jMg',
    'container.build_id' => '18ab1d9c',
    'container.build_time' => 1548767635,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerE595jMg');
