<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZcWTc8r\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZcWTc8r/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZcWTc8r.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZcWTc8r\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZcWTc8r\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZcWTc8r',
    'container.build_id' => 'cc5fc4b9',
    'container.build_time' => 1551183759,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZcWTc8r');
