<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMFvErA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMFvErA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQMFvErA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQMFvErA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQMFvErA\srcDevDebugProjectContainer([
    'container.build_hash' => 'QMFvErA',
    'container.build_id' => '6d7bceb9',
    'container.build_time' => 1556272158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMFvErA');
